
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 20 11:21:07 CEST 2017
//----------------------------------------------------

package source;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RINDEX = 48;
  public static final int INCREMENT = 40;
  public static final int CONST = 6;
  public static final int MULASSIGN = 37;
  public static final int NUMCONST = 18;
  public static final int LPAREN = 45;
  public static final int CONTINUE = 15;
  public static final int DECREMENT = 41;
  public static final int FOR = 13;
  public static final int MINUS = 22;
  public static final int RPAREN = 46;
  public static final int STATIC = 16;
  public static final int PLUSASSIGN = 35;
  public static final int SEMICOLON = 42;
  public static final int AND = 32;
  public static final int LCURLYBRACE = 49;
  public static final int MINUSASSIGN = 36;
  public static final int DIVASSIGN = 38;
  public static final int OR = 33;
  public static final int COMMA = 43;
  public static final int CLASS = 4;
  public static final int DIV = 24;
  public static final int PLUS = 21;
  public static final int ASSIGN = 34;
  public static final int IF = 7;
  public static final int DOT = 44;
  public static final int LE = 30;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 23;
  public static final int MOD = 25;
  public static final int BREAK = 3;
  public static final int IDENT = 17;
  public static final int MODASSIGN = 39;
  public static final int VOID = 12;
  public static final int EQU = 26;
  public static final int ELSE = 5;
  public static final int GTEQU = 29;
  public static final int READ = 10;
  public static final int CHARCONST = 19;
  public static final int NOTEQU = 27;
  public static final int BOOLCONST = 20;
  public static final int EXTENDS = 14;
  public static final int LEQU = 31;
  public static final int RCURLYBRACE = 50;
  public static final int GT = 28;
  public static final int LINDEX = 47;
  public static final int PRINT = 9;
}

